### PR TITLE
fix(source): HLS would not work if used directly.

### LINKED ISSUE #257: HLS stream would panic
**Songbird version:** 0.4.3

**Rust version (`rustc -V`):** rustc 1.81.0 (eeb90cda1 2024-09-04)

**Description:**

The program panicked in rusty pool thread when using `HlsRequest`

```
thread 'rusty_pool_1_thread_1' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stream_lib-0.5.2/src/hls/mod.rs:99:9:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
```

**Steps to reproduce:**

```rust
let input = HlsRequest::new(...).into();
driver.play_only_input(input);
```

### PR DESCRIPTION
**Pull request by Erk-**
This changes HlsRequest to return true in
Compose::should_create_async.

This would otherwise cause it to be spawned on a thread without a
executor causing it to panic.

This would only cause issues if used directly since we otherwise use
Compose::create in a context where we have access to the executor.

Closes #257 

## Open questions:

- [x] Should the `create` implementation be removed or have a note that it will panic if called outside of a tokio executor?

### CODE REVIEW

**Comment by Erk-** [comment]
The fails in the tests seems to be that beta and nightly catches more examples of missing documentation and is not caused by this patch.

**Review by kane50613 — APPROVED** [review]

**Review by FelixMcFelix — APPROVED** [review]
Looks good to me, thanks for figuring this out. Yeah, CI failures are down to a change in how a lint is applied.

**Comment by FelixMcFelix** [comment]
>     * [ ]  Should the `create` implementation be removed or have a note that it will panic if called outside of a tokio executor?

I think a note indicating the panic would be most useful here. It is still feasible to call, so it doesn't violate the existing API contract but it's better to not surprise users where possible!

**Comment by Erk-** [comment]
I added a note about it on the struct

**Comment by FelixMcFelix** [comment]
Thanks for the fix; feel free to merge when you're ready (I believe you have access?).

**Pull request merged**
