### PR TITLE
Fix serenity breaking changes

### PR DESCRIPTION
**Pull request by tazz4843**
Caused by serenity-rs/serenity#2372.

Currently untested, will test when I get a chance to do so.

### CODE REVIEW

**Comment by kangalio** [comment]
As the one who made the breaking PR - can you give feedback, do the changes seem logical? I see you had to change `serenity::gateway::InterMessage` to `serenity::client::bridge::gateway::ShardRunnerMessage`. The upcoming https://github.com/serenity-rs/serenity/pull/2380 will change the ugly long path to be `serenity::gateway::ShardRunnerMessage` again.

**Comment by tazz4843** [comment]
I was very confused as to what `InterMessage` got replaced with. The changelog entry you provided in the linked PR didn't really help to provide a replacement, so I had to look through the commits to discover.

**Comment by kangalio** [comment]
> I was very confused as to what `InterMessage` got replaced with. The changelog entry you provided in the linked PR didn't really help to provide a replacement, so I had to look through the commits to discover.

Thanks, you're right. I amended some additional context in https://github.com/serenity-rs/serenity/pull/2372#issuecomment-1501181383

**Comment by tazz4843** [comment]
Since serenity-rs/serenity#2380 is coming soon, this PR should probably wait for it to be merged.

**Comment by FelixMcFelix** [comment]
@tazz4843 I've re-run CI, serenity-rs/serenity#2380 has indeed broken the fix.

**Comment by kangalio** [comment]
To update, just replace `serenity::client::bridge::gateway` with `serenity::gateway` in the code

**Pull request merged**
